/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Dominio.Sistema;
import java.awt.Image;
import java.io.File;
import javafx.stage.FileChooser;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author Juan
 */
public class frameCambiarFicha extends javax.swing.JFrame {

    Image fichaNegra;
    Image fichaBlanca;
    boolean cambioBlanca = false;
    boolean cambioNegra = false;

    /**
     * Creates new form frameCambiarFicha
     */
    public frameCambiarFicha(Sistema sis) {

        unSistema = sis;
        initComponents();
        ImageIcon blanco = new ImageIcon(unSistema.getPartidaActual().getFichaJBlanco().getScaledInstance(25, 25, java.awt.Image.SCALE_SMOOTH));
        ImageIcon negro = new ImageIcon(unSistema.getPartidaActual().getFichaJNegro().getScaledInstance(25, 25, java.awt.Image.SCALE_SMOOTH));

        jLabel1.setIcon(blanco);
        jLabel1.setIcon(negro);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        btnBlanco = new javax.swing.JButton();
        btnNegro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBlanco.setText("Blkanco");
        btnBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlancoActionPerformed(evt);
            }
        });

        btnNegro.setText("Negro");
        btnNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegroActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNegro)
                    .addComponent(jLabel2))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBlanco)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnBlanco)
                .addGap(1, 1, 1)
                .addComponent(btnNegro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlancoActionPerformed
        Image img = null;
        boolean esCorrecta = false;
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                img = ImageIO.read(file);
                img = img.getScaledInstance(25, 25, java.awt.Image.SCALE_SMOOTH);

                ImageIcon blanco = new ImageIcon(img);

                jLabel1.setIcon(blanco);
                esCorrecta = true;
            } catch (Exception a) {

                JOptionPane.showMessageDialog(this, "Formato no permitido", "Formato Incorrecto", ERROR_MESSAGE);

            }
            if (esCorrecta) {

                fichaBlanca = img;

            }
        } else {
            System.out.println("El usuario no cargo imagen");
        }
    }//GEN-LAST:event_btnBlancoActionPerformed

    private void btnNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegroActionPerformed
        Image imgNegra = null;
        boolean esCorrecta = false;
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                imgNegra = ImageIO.read(file);
                imgNegra = imgNegra.getScaledInstance(25, 25, java.awt.Image.SCALE_SMOOTH);

                ImageIcon negro = new ImageIcon(imgNegra);

                jLabel2.setIcon(negro);
                esCorrecta = true;
            } catch (Exception a) {

                JOptionPane.showMessageDialog(this, "Formato no permitido", "Formato Incorrecto", ERROR_MESSAGE);

            }
            if (esCorrecta) {
                fichaNegra = imgNegra;

            }
        } else {
            System.out.println("El usuario no cargo imagen");
        }
    }//GEN-LAST:event_btnNegroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro desea abandonar la partida?");
        if (resp == 1) {

            if (cambioBlanca && cambioNegra) {
                unSistema.getPartidaActual().setFichaJBlanco(fichaBlanca);
                unSistema.getPartidaActual().setFichaJNegro(fichaNegra);
                this.dispose();
            }
            if (!cambioBlanca && cambioNegra) {

                unSistema.getPartidaActual().setFichaJNegro(fichaNegra);

            }
            if (cambioBlanca && !cambioNegra) {
                unSistema.getPartidaActual().setFichaJBlanco(fichaBlanca);
                unSistema.getPartidaActual().setFichaJNegro(fichaNegra);
                this.dispose();
            }
            if (!cambioBlanca && !cambioNegra) {

                this.dispose();
            }

        } else {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frameCambiarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frameCambiarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frameCambiarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frameCambiarFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frameCambiarFicha().setVisible(true);
//            }
//        });
    }
    Sistema unSistema = new Sistema();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlanco;
    private javax.swing.JButton btnNegro;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
